/* Which "<category>/<service>" pairs have a working tool component.

   Plain data with no component imports, so a Server Component can ask "is there
   a tool here?" without pulling any tool code into the server graph. The
   components themselves are mounted by components/ToolMount.jsx.

   Generated from the registry — keep in step with ToolMount's loader map. */

export const TOOL_KEYS = new Set([
  // Developer tools
  "tools/json-formatter",
  "tools/base64-encoder",
  "tools/url-encoder",
  "tools/jwt-decoder",
  "tools/uuid-generator",
  "tools/hash-generator",
  "tools/password-generator",
  "tools/regex-tester",
  "tools/markdown-previewer",
  "tools/color-converter",
  "tools/gradient-generator",
  "tools/box-shadow-generator",
  "tools/border-radius-generator",
  "tools/qr-code-generator",
  "tools/lorem-ipsum",
  "tools/xml-formatter",
  "tools/html-formatter",
  "tools/yaml-formatter",
  "tools/sql-formatter",
  "tools/css-minifier",
  "tools/js-minifier",
  "tools/csv-converter",
  "tools/random-number",
  "tools/dice-coin",
  "tools/spin-wheel",
  "tools/color-contrast",
  "tools/url-shortener",
  "tools/barcode-generator",
  "tools/json-to-typescript",
  "tools/cron-expression",
  "tools/html-to-markdown",
  "tools/password-strength",
  "tools/link-in-bio",
  // Image
  "image/image-resizer",
  "image/image-cropper",
  "image/image-compressor",
  "image/image-to-base64",
  "image/image-to-text",
  "image/favicon-generator",
  "image/meme-generator",
  "image/color-palette",
  "image/text-to-handwriting",
  "image/placeholder-image",
  "image/poster-maker",
  // Games
  "games/game-2048",
  "games/snake",
  "games/tic-tac-toe",
  "games/would-you-rather",
  // Files & PDF
  "files/pdf-merge",
  "files/pdf-split",
  "files/pdf-compress",
  "files/images-to-pdf",
  "files/pdf-esign",
  "files/image-converter",
  "files/social-image-resizer",
  "files/screen-recorder",
  "files/certificate-generator",
  // Text
  "text/word-counter",
  "text/case-converter",
  "text/text-diff",
  "text/remove-duplicate-lines",
  "text/sort-lines",
  "text/reverse-text",
  "text/find-replace",
  "text/text-repeater",
  "text/text-to-speech",
  "text/speech-to-text",
  "text/emoji-picker",
  "text/prompt-optimizer",
  "text/paraphrasing-tool",
  // Calculators
  "calculators/percentage-calculator",
  "calculators/bmi-calculator",
  "calculators/age-calculator",
  "calculators/loan-calculator",
  "calculators/tip-calculator",
  "calculators/discount-calculator",
  "calculators/mortgage-calculator",
  "calculators/compound-interest",
  "calculators/calorie-calculator",
  "calculators/gpa-calculator",
  "calculators/scientific-calculator",
  "calculators/sip-calculator",
  "calculators/income-tax-calculator",
  "calculators/gst-calculator",
  "calculators/date-calculator",
  // Converters
  "converters/unit-converter",
  "converters/number-base-converter",
  "converters/roman-numeral-converter",
  "converters/timestamp-converter",
  "converters/morse-code",
  "converters/currency-converter",
  // SEO
  "seo/meta-tag-generator",
  "seo/open-graph-generator",
  "seo/twitter-card-generator",
  "seo/schema-generator",
  "seo/heading-checker",
  "seo/sitemap-generator",
  "seo/robots-txt-generator",
  "seo/slug-generator",
  "seo/keyword-density",
  // Productivity
  "productivity/notes",
  "productivity/todo",
  "productivity/kanban",
  "productivity/pomodoro",
  "productivity/habit-tracker",
  "productivity/goal-tracker",
  "productivity/expense-tracker",
  "productivity/bookmark-manager",
  "productivity/stopwatch",
  "productivity/countdown",
  "productivity/typing-test",
  "productivity/survey-maker",
  "productivity/meeting-scheduler",
  "productivity/presentation-maker",
  "productivity/flashcard-maker",
  // Career
  "career/resume-builder",
  "career/resume-template-builder",
  "career/cover-letter",
  "career/salary-calculator",
  // Freelance
  "freelance/invoice-generator",
  "freelance/time-tracker",
  // Social Media
  "social/video-downloader",
  "social/hashtag-generator",
  "social/fancy-text-generator",
  "social/youtube-thumbnail",
  "social/youtube-embed",
  "social/social-character-counter",
  "social/utm-builder",
  "social/wedding-hashtag-generator",
  // AI Tools (free, no API key)
  "ai/ai-assistant",
  "ai/ai-cover-letter",
  "ai/resume-bullet-generator",
  "ai/ai-email-writer",
  "ai/business-name-generator",
  "ai/slogan-generator",
  "ai/ai-image-prompt",
]);

export function hasTool(categorySlug, serviceSlug) {
  return TOOL_KEYS.has(`${categorySlug}/${serviceSlug}`);
}
